//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArnelAves_Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmortizationSchedule
    {
        public int AmortizationID { get; set; }
        public Nullable<int> ScheduleOrderNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<double> PrincipalAmount { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<double> InterestAmount { get; set; }
        public Nullable<double> DueAmount { get; set; }
        public Nullable<double> RemainingBalance { get; set; }
        public Nullable<int> DaysInterval { get; set; }
        public Nullable<int> SessionNumber { get; set; }
    
        public virtual ConsumerLoanSsession ConsumerLoanSsession { get; set; }
    }
}
