//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArnelAves_Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerLoanSsession
    {
        public ConsumerLoanSsession()
        {
            this.AmortizationSchedules = new HashSet<AmortizationSchedule>();
        }
    
        public int SessionNumber { get; set; }
        public System.DateTime SessionTimeStamp { get; set; }
        public Nullable<double> LoanAmount { get; set; }
        public Nullable<double> LoanTenure { get; set; }
        public Nullable<double> LoanInterest { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual ICollection<AmortizationSchedule> AmortizationSchedules { get; set; }
    }
}
